version: '3.7'
services:
  apache:
    container_name: amaury_apache
    hostname: amaury_apache
    build: ./containers/apache
    ports:
      - '80:80' # 1er : port de mac os; 2e : port du conteneur docker
      - '443:443'
    networks:
      - amaury-lamp
    volumes:
      - './src/:/usr/local/apache2/htdocs'
      - './config/:/usr/local/apache2/conf/extra'
  php:
    container_name: amaury_php
    hostname: amaury_php
    build: ./containers/php
    networks:
      - amaury-lamp
    volumes:
      - './src/:/var/www/html'
  mysql:
    container_name: amaury_mysql
    hostname: amaury_mysql
    build: ./containers/mysql
    ports: 
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - amaury-lamp
networks:
  amaury-lamp: